[window]
  opacity = 0.95
[font]
size = 12

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.bold]
family = "Berkeley Mono"
style = "Regular"

[font.italic]
family = "Berkeley Mono"
style = "Regular"

[font.bold_italic]
family = "Berkeley Mono"
style = "Regular"
